export interface BookingPlatformInfo {
  platform: "Marham" | "Oladoc" | "SehatKahani";
  link?: string;
}

export interface Doctor {
  name: string;
  nameUr: string;
  city: string;
  specialization: string;
  contactNumber: string;
  pmdcNumber: string;
  bookingPlatforms: BookingPlatformInfo[];
}

export const specializationTranslations: Record<string, string> = {
  "Bariatric Surgeon": "بیریاٹرک سرجن",
  "Endocrinology": "غدد کی بیماریاں",
  "Endocrinologist": "غدد کے ماہر",
  "Diabetes/Obesity": "ذیابیطس/موٹاپا",
  "Family Medicine / Public Health": "فیملی میڈیسن / صحت عامہ",
  "Diabetologist": "ذیابیطس کے ماہر",
  "Diabetology": "ذیابیطس کے ماہر",
  "Medicine": "طب",
  "Physician": "معالج",
  "Cardiologist": "امراض قلب کے ماہر",
};

export const cityTranslations: Record<string, string> = {
  Mardan: "مردان",
  Rawalpindi: "راولپنڈی",
  "Islamabad/Peshawar": "اسلام آباد/پشاور",
  Islamabad: "اسلام آباد",
  Sialkot: "سیالکوٹ",
  Gujranwala: "گجرانوالا",
  Multan: "ملتان",
  Faisalabad: "فیصل آباد",
  Peshawar: "پشاور",
  Lahore: "لاہور",
  Sukkur: "سکھر",
  Hyderabad: "حیدرآباد",
  Karachi: "کراچی",
};

export const doctors: Doctor[] = [
  {
    name: "Dr Bayazeed",
    nameUr: "ڈاکٹر بیازید",
    city: "Mardan",
    specialization: "Bariatric Surgeon",
    contactNumber: "0345-9857944",
    pmdcNumber: "17797-N",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Adnan Zahid",
    nameUr: "ڈاکٹر عدنان زاہد",
    city: "Rawalpindi",
    specialization: "Endocrinology",
    contactNumber: "0321-5071061",
    pmdcNumber: "50254-P",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Muhammad Umar Wahab",
    nameUr: "ڈاکٹر محمد عمر وہاب",
    city: "Islamabad/Peshawar",
    specialization: "Diabetes/Obesity",
    contactNumber: "0333-9158285",
    pmdcNumber: "13174-N",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Ahmed Abdullah",
    nameUr: "ڈاکٹر احمد عبداللہ",
    city: "Rawalpindi",
    specialization: "Family Medicine / Public Health",
    contactNumber: "0333-5494758",
    pmdcNumber: "50155-P",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Kashif Rasheed",
    nameUr: "ڈاکٹر کاشف رشید",
    city: "Islamabad",
    specialization: "Endocrinology",
    contactNumber: "0333-5304789",
    pmdcNumber: "53791-P",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Usama Sohail",
    nameUr: "ڈاکٹر اسامہ سہیل",
    city: "Sialkot",
    specialization: "Diabetologist",
    contactNumber: "0343-4147898",
    pmdcNumber: "114912-P*",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "SehatKahani" }],
  },
  {
    name: "Dr Amjad Iqbal",
    nameUr: "ڈاکٹر امجد اقبال",
    city: "Gujranwala",
    specialization: "Diabetologist",
    contactNumber: "0300-9648828",
    pmdcNumber: "17676-P",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Irfan Sheikh",
    nameUr: "ڈاکٹر عرفان شیخ",
    city: "Multan",
    specialization: "Diabetologist",
    contactNumber: "0301-7410205",
    pmdcNumber: "7046-P",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "SehatKahani" }],
  },
  {
    name: "Dr Altaf Ur Rehman",
    nameUr: "ڈاکٹر الطاف الرحمان",
    city: "Faisalabad",
    specialization: "Diabetologist",
    contactNumber: "0302-8643100",
    pmdcNumber: "24718-P",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "SehatKahani" }],
  },
  {
    name: "Dr Fahim Ullah",
    nameUr: "ڈاکٹر فہیم اللہ",
    city: "Peshawar",
    specialization: "Endocrinology",
    contactNumber: "0332-9142021",
    pmdcNumber: "13826-N",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Muhammad Azmat Khan",
    nameUr: "ڈاکٹر محمد عزمت خان",
    city: "Rawalpindi",
    specialization: "Medicine",
    contactNumber: "0333-5179501",
    pmdcNumber: "455-AJK",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Bilal Bin Younus",
    nameUr: "ڈاکٹر بلال بن یونس",
    city: "Lahore",
    specialization: "Medicine",
    contactNumber: "0300-9405405",
    pmdcNumber: "12147-P",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr M Tahir Chaudhry",
    nameUr: "ڈاکٹر محمد طاہر چوہدری",
    city: "Lahore",
    specialization: "Diabetology",
    contactNumber: "0300-9448693",
    pmdcNumber: "20817-P",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Madeeha Nazar",
    nameUr: "ڈاکٹر مدیحہ نذر",
    city: "Rawalpindi",
    specialization: "Endocrinology",
    contactNumber: "0332-7777658",
    pmdcNumber: "45679-P",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Musarrat Iqbal",
    nameUr: "ڈاکٹر مسرت اقبال",
    city: "Islamabad",
    specialization: "Diabetologist",
    contactNumber: "0302-5450011",
    pmdcNumber: "12006-S",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Faheem Ullah",
    nameUr: "ڈاکٹر فہیم اللہ",
    city: "Peshawar",
    specialization: "Endocrinology",
    contactNumber: "0301-8502888",
    pmdcNumber: "19868-N",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Zahid Mehmood",
    nameUr: "ڈاکٹر زاہد محمود",
    city: "Rawalpindi",
    specialization: "Diabetologist",
    contactNumber: "0333-5628541",
    pmdcNumber: "8106-N",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Muhammad Iqbal",
    nameUr: "ڈاکٹر محمد اقبال",
    city: "Rawalpindi",
    specialization: "Diabetology",
    contactNumber: "0307-5113504",
    pmdcNumber: "1112-AJK",
    bookingPlatforms: [
      { platform: "Marham" },
      { platform: "Oladoc" },
      { platform: "SehatKahani" },
    ],
  },
  {
    name: "Dr Hafiz Ahsan",
    nameUr: "ڈاکٹر حافظ احسن",
    city: "Lahore",
    specialization: "Diabetology",
    contactNumber: "0322-4383054",
    pmdcNumber: "50794-P",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "Oladoc" }],
  },
  {
    name: "Dr Syed Sohaib Haider Zadi",
    nameUr: "ڈاکٹر سید صہیب حیدر زیدی",
    city: "Lahore",
    specialization: "Endocrinology",
    contactNumber: "0333-8776350",
    pmdcNumber: "45931-P",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "Oladoc" }],
  },
  {
    name: "Dr Shahzad tahir",
    nameUr: "ڈاکٹر شہزاد طاہر",
    city: "Rawalpindi",
    specialization: "Diabetology",
    contactNumber: "03005144156",
    pmdcNumber: "26615-P",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "Oladoc" }],
  },
  {
    name: "Dr Col Fawad Rehman",
    nameUr: "ڈاکٹر کرنل فواد رحمان",
    city: "Rawalpindi",
    specialization: "Physician",
    contactNumber: "0313-5256261",
    pmdcNumber: "40189-P",
    bookingPlatforms: [{ platform: "Marham" }],
  },
  {
    name: "Dr Wasiq Zafar Abbasi",
    nameUr: "ڈاکٹر واثق ظفر عباسی",
    city: "Rawalpindi",
    specialization: "Physician",
    contactNumber: "0333-6422274",
    pmdcNumber: "16030-P",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "Oladoc" }],
  },
  {
    name: "Dr Saleem Qureshi",
    nameUr: "ڈاکٹر سلیم قریشی",
    city: "Islamabad",
    specialization: "Physician",
    contactNumber: "03205450688",
    pmdcNumber: "1764-p",
    bookingPlatforms: [{ platform: "Marham" }, { platform: "Oladoc" }],
  },
  {
    name: "Dr Tariq Sawand",
    nameUr: "ڈاکٹر طارق ساوند",
    city: "Sukkur",
    specialization: "Cardiologist",
    contactNumber: "3337301525",
    pmdcNumber: "32698-S",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Saleem Khan",
    nameUr: "ڈاکٹر سلیم خان",
    city: "Hyderabad",
    specialization: "Endocrinologist",
    contactNumber: "3332636673",
    pmdcNumber: "60468-S",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Asma Ahmed",
    nameUr: "ڈاکٹر اسماء احمد",
    city: "Karachi",
    specialization: "Endocrinologist",
    contactNumber: "3018215464",
    pmdcNumber: "39382-2",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Nadeem Naeem",
    nameUr: "ڈاکٹر ندیم نعیم",
    city: "Karachi",
    specialization: "Endocrinologist",
    contactNumber: "3009395600",
    pmdcNumber: "55072-S",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Musarrat Riaz",
    nameUr: "ڈاکٹر مسرت ریاض",
    city: "Karachi",
    specialization: "Endocrinologist",
    contactNumber: "3333608865",
    pmdcNumber: "31508-S",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Tahir Ansari",
    nameUr: "ڈاکٹر طاہر انصاری",
    city: "Karachi",
    specialization: "Physician",
    contactNumber: "3112477724",
    pmdcNumber: "35100-S",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Yusuf Kamal",
    nameUr: "ڈاکٹر یوسف کمال",
    city: "Karachi",
    specialization: "Physician",
    contactNumber: "3332154522",
    pmdcNumber: "P-34703",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Urooj Laal",
    nameUr: "ڈاکٹر عروج لال",
    city: "Karachi",
    specialization: "Endocrinologist",
    contactNumber: "3045153188",
    pmdcNumber: "P-41278",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Imran Ul Haq",
    nameUr: "ڈاکٹر عمران الحق",
    city: "Karachi",
    specialization: "Endocrinologist",
    contactNumber: "3343556355",
    pmdcNumber: "S-45026",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Asher Fawad",
    nameUr: "ڈاکٹر عاشر فواد",
    city: "Karachi",
    specialization: "Physician",
    contactNumber: "3302323905",
    pmdcNumber: "3507-P",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Amin Abdullah Makki",
    nameUr: "ڈاکٹر امین عبداللہ مکی",
    city: "Karachi",
    specialization: "Diabetologist",
    contactNumber: "3330245765",
    pmdcNumber: "13887-S",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Dr Nida Shakeel",
    nameUr: "ڈاکٹر ندا شکیل",
    city: "Karachi",
    specialization: "Physician",
    contactNumber: "3181144469",
    pmdcNumber: "48669-S",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
  {
    name: "Usama Sohail",
    nameUr: "اسامہ سہیل",
    city: "Lahore",
    specialization: "Diabetologist",
    contactNumber: "0343 4147898",
    pmdcNumber: "34969-P",
    bookingPlatforms: [{ platform: "Oladoc" }],
  },
];

// Helper functions to get unique values for filters
export const getUniqueCities = (): string[] => {
  const cities = doctors.map((doctor) => doctor.city);
  return Array.from(new Set(cities)).sort();
};

export const getUniqueSpecializations = (): string[] => {
  const specializations = doctors.map((doctor) => doctor.specialization);
  return Array.from(new Set(specializations)).sort();
};

export const bookingPlatforms = ["Marham", "Oladoc", "SehatKahani"] as const;
